apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "certificate-manager.fullname" . }}-role
rules:
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch


