---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "certificate-manager.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "certificate-manager.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "certificate-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
