# permissions for end users to edit certificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: certificate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-manager
    app.kubernetes.io/part-of: certificate-manager
    app.kubernetes.io/managed-by: kustomize
  name: certificate-editor-role
rules:
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates/status
  verbs:
  - get
