apiVersion: certs.k8c.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: certificate-sample
    app.kubernetes.io/part-of: certificate-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: certificate-manager
  name: certificate-sample
spec:
  dnsName: example.k8c.io
  validity: 360d
  secretRef:
    name: my-certificate-secret
  purgeOnDelete: false
  reloadOnChange: false
  rotateOnExpiry: false
