apiVersion: certs.k8c.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: default
spec:
  # the DNS name for which the certificate should be issued
  dnsName: example.k8c.io
  # the time until the certificate expires
  validity: 360d
  # a reference to the Secret object in which the certificate is stored
  secretRef:
    name: my-certificate-secret
  # optional: purgeOnDelete will delete the secret when the certificate CR is deleted
  purgeOnDelete: true
  # optional: reloadOnChange will reload the deployments using the secret when the certificate is updated
  reloadOnChange: false
  # optional: rotateOnExpiry will rotate the certificate before it expires
  rotateOnExpiry: false